### ISSUE TITLE
Display serialized data

### ISSUE THREAD

**Issue by szepeviktor** [erikdubbelboer/phpRedisAdmin#100]
Could we have

```php
function maybe_unserialize( $original ) {
    if ( is_serialized( $original ) ) // don't attempt to unserialize data that wasn't serialized going in
        return @unserialize( $original );
    return $original;
}
```

and if it is serialized then `<pre class="data"><?php var_export($data); ?></pre>` to show data?

**Comment by erikdubbelboer** [comment]
You can add these to the [config.php](https://github.com/erikdubbelboer/phpRedisAdmin/blob/master/includes/config.sample.inc.php#L60-L67) and add them as [serialization functions](https://github.com/erikdubbelboer/phpRedisAdmin/blob/master/includes/config.sample.inc.php#L60-L67).

**Comment by szepeviktor** [comment]
Thank you.
High-tech.
