### ISSUE TITLE
unable to visit

### ISSUE THREAD

**Issue by 269941633** [erikdubbelboer/phpRedisAdmin#106]
Warning: require(/var/www/html/includes/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/includes/common.inc.php on line 2 Fatal error: require(): Failed opening required '/var/www/html/includes/../vendor/autoload.php' (include_path='.:/usr/local/php-5.3.29/lib/php') in /var/www/html/includes/common.inc.php on line 2

**Comment by erikdubbelboer** [comment]
Documentation on how to install can be found in the readme: https://github.com/erikdubbelboer/phpRedisAdmin#installingconfiguring
