### ISSUE TITLE
homebrew

### ISSUE THREAD

**Issue by ruurd** [erikdubbelboer/phpRedisAdmin#109]
Can you be interested in adding a recipe for homebrew?

**Comment by erikdubbelboer** [comment]
Sure, but I have never used homebrew before so someone else will have to create and test it.

**Comment by ruurd** [comment]
Erik would it be cumbersome to add the vendor subdirectory to a release? So that the release artifact can be used without any additional installation?

**Comment by erikdubbelboer** [comment]
I prefer not to do this as this would mean I have to release an update every time predis gets an update.

**Comment by ruurd** [comment]
hmmm you've got a point there. ok need to find a way to git clone the extra stuff in the right place.
