### ISSUE TITLE
Can I connect to redis inside vm

### ISSUE THREAD

**Issue by eslam-mahmoud** [erikdubbelboer/phpRedisAdmin#114]
Hello, 

I am using Vagrant virtual box and have redis server installed inside 
I tried to add the ip of virtual box as host and set the port and auth but getting 

> ERROR: Connection refused [tcp://{ip}:6379]

any help with that ?

**Comment by erikdubbelboer** [comment]
This has nothing to do with phpRedisAdmin. Sounds like you need to setup proper networking to and from your VM which I'm afraid I can't help with. I suggest reading the Virtual Box documentation or asking on some Virtual Box support place.
