### ISSUE TITLE
Typo in config.sample.inc.php

### ISSUE THREAD

**Issue by snacaman** [erikdubbelboer/phpRedisAdmin#117]
Hello. In config.sample.inc.php:39 is sep**e**rator instead of sep**a**rator. It seems to be a typo. Isn't it? This variable name is also used in other places in code.

Regards.

**Comment by erikdubbelboer** [comment]
That is stupid, it's one of those works I consistently mistype. It's also unfortunate cause if we fix it we break everyone's config when they upgrade :( So I'm just going to keep it.
