### ISSUE TITLE
Composer.lock out of sync?

### ISSUE THREAD

**Issue by theycallmepepper** [erikdubbelboer/phpRedisAdmin#119]
Checked out tag v1.8.0 and upon running composer install I receive:

> Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

Not really an issue but shouldn't this come up clean on a release?  
> composer update --lock

^ at least clears up the message.

**Comment by erikdubbelboer** [comment]
Not quite sure why the hash and timestamp format changed as the version stayed exactly the same. But I hope this fixes the issue.
