### ISSUE TITLE
Error 500 after installation

### ISSUE THREAD

**Issue by AKACC** [erikdubbelboer/phpRedisAdmin#121]
PHP Fatal error:  Uncaught Predis\\Response\\ServerException: ERR Client sent AUTH, but no password is set in ...public/phpRedisAdmin/vendor/predis/predis/src/Client.php on line 365

**Comment by erikdubbelboer** [comment]
Sounds like you set a password in the config while not having a password configured in your redis instance:
https://github.com/erikdubbelboer/phpRedisAdmin/blob/f3000673c5c67811c3da8c12395d2cf6974d406a/includes/config.sample.inc.php#L15

**Comment by AKACC** [comment]
Thanks for replying. I changed this part and fill up with all possible passwords, but it still does not work. And do you mean I set a password of apache?

**Comment by AKACC** [comment]
@erikdubbelboer I commented it out and it works!! Thanks!!
