### ISSUE TITLE
How to install phpRedisAdmin in cPanel

### ISSUE THREAD

**Issue by Nirjonadda** [erikdubbelboer/phpRedisAdmin#123]
Please let me know that How to install phpRedisAdmin in cPanel on CentOS 7.4?

**Comment by erikdubbelboer** [comment]
I have never used cPanel before so I have no idea.

**Comment by Nirjonadda** [comment]
@erikdubbelboer Then do you know that how to install phpRedisAdmin in CentOS 7?

**Comment by erikdubbelboer** [comment]
@Nirjonadda just read the normal install instructions: https://github.com/erikdubbelboer/phpRedisAdmin#installingconfiguring
