### ISSUE TITLE
docker image not supply setting redis password

### ISSUE THREAD

**Issue by guodidi** [erikdubbelboer/phpRedisAdmin#125]
hi , i want to use the project docker image , but my redis has password , i reading the `config.sample.inc.php`, and did fount anywhere to setting my password . it that say the docker image not supply the function ? and what should i do to add the function for docker image, thank you

**Comment by erikdubbelboer** [comment]
I think setting the password is described in this issue: https://github.com/erikdubbelboer/phpRedisAdmin/pull/72 otherwise I think @pataquets can help.

**Comment by pataquets** [comment]
@guodidi : Configuration is done via environment variables ad can be seen here:
https://github.com/erikdubbelboer/phpRedisAdmin/blob/master/includes/config.environment.inc.php
The only user/password that the file loads from env vars is for auth'ing to pRA, but password for Redis instances is not covered. It should be trivial, since there is an 'auth' key which should be mapped to the corresponding REDIS_N_AUTH env var. See https://github.com/erikdubbelboer/phpRedisAdmin/blob/master/includes/config.sample.inc.php
It should be fairly trivial to add (just have to keep the array item unset if no env var) and I might be able to do it myself if I find some spare time, but no commitment here. However if you beat me at it, I'll take a look and update the docs and related Docker files.

**Comment by guodidi** [comment]
@pataquets @erikdubbelboer thanks for your reply. i am so sorry for i forget to resolve this issue . i think it a better choise to add get env variable for every redis instance password. 

it is my resolve 

```
<?php

include 'config.sample.inc.php';

$admin_user = getenv('ADMIN_USER');
$admin_pass = getenv('ADMIN_PASS');

if (!empty($admin_user)) {
  $config['login'] = array(
    $admin_user => array(
      'password' => $admin_pass,
    ),
  );
}

$i=1;
$config['servers'] = array();

while (TRUE) {

  $prefix = 'REDIS_' . $i . '_';

  $server_name = getenv($prefix . 'NAME');
  $server_host = getenv($prefix . 'HOST');
  $server_port = getenv($prefix . 'PORT');
  $server_auth = getenv($prefix . 'AUTH');

  if (empty($server_host)) {
    break;
  }

  if (empty($server_name)) {
    $server_name = $server_host;
  }
  
  if (empty($server_auth)) {
    $server_auth = "";
  } 

  if (empty($server_port)) {
    $server_port = 6379;
  }

  $config['servers'][] = array(
      'name'   => $server_name,
      'host'   => $server_host,
      'port'   => $server_port,
      'filter' => '*',
  );
  
  if (!empty($server_auth)) {
    $config['servers'][$i-1]['auth'] = $server_auth;
  } 

  $i++;
}
```

Dockerfile 

```
FROM erikdubbelboer/phpredisadmin
COPY config.environment.inc.php /src/app/includes/config.inc.php
```

env file 
```
REDIS_1_HOST=localhost
REDIS_1_PORT=8000
REDIS_1_NAME=8000-redis

REDIS_2_HOST=localhost
REDIS_2_PORT=6380
REDIS_2_NAME=6380-redis
REDIS_1_AUTH=mypassword
```

**Comment by pataquets** [comment]
@guodidi : LGTM. Fancy to submit a PR?
@erikdubbelboer : any comments?

**Comment by pataquets** [comment]
Not sure, but perhaps using ```current()``` instead of ```$i - 1``` to reference last inserted item is more safe, if array item appending change. Or maybe not, just a thought.

**Comment by erikdubbelboer** [comment]
Yes please a PR would be nice. I think `$i - 1` is fine.

**Comment by shynome** [comment]
I also need this option to set redis password , because I use a exist redis server that can't link the docker network

**Comment by shynome** [comment]
I found the docker image `erikdubbelboer/phpredisadmin:v1.11.0` now can set env `REDIS_1_AUTH` . 

when I proxy the docker image to `/phpredisadmin/` by caddy I get a problem, the css is 404, I use the caddy config to solve it, hope can help someone
```conf
http://0.0.0.0:80 {
  
  proxy /phpredisadmin/ phpredisadmin:80 {
    transparent
    without /phpredisadmin/
  }

}
```

**Comment by erikdubbelboer** [comment]
The changes from this issue were already merged, see: https://github.com/erikdubbelboer/phpRedisAdmin/blob/ed5966f637ceda71b63693bd3d8fd336a840d01a/includes/config.environment.inc.php

I think your `without` statement needs to be `without /phpredisadmin`. But this is not really the place to discuss caddy issues.
