### ISSUE TITLE
Concrete version

### ISSUE THREAD

**Issue by MattCzerner** [erikdubbelboer/phpRedisAdmin#127]
Hi, is there chance to tag version of your image, im trying to make sure that my application will be always built and I had some troubles with images at latest version.

Is there any reason for not creating concrete version?

**Comment by erikdubbelboer** [comment]
I have tagged `v1.10.2`.

The issue is that docker hub is broken and doesn't automatically build a new version when I tag a release in GitHub. I hope I remember to add a new release there as well each time I tag one here.

**Comment by MattCzerner** [comment]
Thank you very much.
