### ISSUE TITLE
Fatal error: Cannot redeclare authCookie() (previously declared in /www/wwwroot/2222.tools/phpRedisAdmin/includes/login.inc.php:75) in /www/wwwroot/2222.tools/phpRedisAdmin/includes/login.inc.php on line 75

### ISSUE THREAD

**Issue by ABC333Love** [erikdubbelboer/phpRedisAdmin#133]
Fatal error: Cannot redeclare authCookie() (previously declared in /www/wwwroot/2222.tools/phpRedisAdmin/includes/login.inc.php:75) in /www/wwwroot/2222.tools/phpRedisAdmin/includes/login.inc.php on line 75

**Comment by erikdubbelboer** [comment]
Thanks, should be fixed in the latest commit.
