### ISSUE TITLE
ERROR: Your key is to long (max length is 100)

### ISSUE THREAD

**Issue by rukavina** [erikdubbelboer/phpRedisAdmin#134]
This error is shown when trying to add a key longer than 100 chars, while the same can be done via redis-cli.

Also, keys longer than 100 chars added via redis-cli are not visible in phpRedisAdmin

**Comment by erikdubbelboer** [comment]
This is a configurable setting: https://github.com/erikdubbelboer/phpRedisAdmin/blob/ed5966f637ceda71b63693bd3d8fd336a840d01a/includes/config.sample.inc.php#L75

**Comment by rukavina** [comment]
Thanks!
