### ISSUE TITLE
use phpRedisAdmin-Docker and Authentication Failed

### ISSUE THREAD

**Issue by rainlay** [erikdubbelboer/phpRedisAdmin#136]
HI, I am using docker to visit redis with password protection,

and run docker command like 

`
sudo docker run --rm -it -e REDIS_1_HOST=172.17.0.1 -e REDIS_1_AUTH=password -e REDIS_1_NAME=redis -p 8080:80 erikdubbelboer/phpredisadmin
`

and visit page, the page show error

`
Fatal error: Uncaught Predis\Response\ServerException: NOAUTH Authentication required. in /src/app/vendor/predis/predis/src/Client.php:365 Stack trace: #0 /src/app/vendor/predis/predis/src/Client.php(330): Predis\Client->onErrorResponse(Object(Predis\Command\KeyScan), Object(Predis\Response\Error)) #1 /src/app/vendor/predis/predis/src/Client.php(309): Predis\Client->executeCommand(Object(Predis\Command\KeyScan)) #2 /src/app/index.php(14): Predis\Client->__call('scan', Array) #3 {main} thrown in /src/app/vendor/predis/predis/src/Client.php on line 365
`

is my environment value setting wrong, or other issue, thanks for reply !

**Comment by erikdubbelboer** [comment]
Did you copy `include/config.environment.inc.php` to `include/config.inc.php`?

**Comment by erikdubbelboer** [comment]
@pataquets Do you have any idea? I'm afraid I don't know anything about Docker.

**Comment by rainlay** [comment]
> docker run --rm -it -e REDIS_1_HOST=172.17.0.1 -e REDIS_1_AUTH=password -e REDIS_1_NAME=redis -p 8080:80 erikdubbelboer/phpredisadmin:v1.11.0

ok, this worked, thanks !!

**Comment by erikdubbelboer** [comment]
Good that you got it working.

I have manually triggered the build for `latest` now to update it as well.

I have no idea why the latest tag doesn't automatically update, it's in the build settings. Docker hub is still one of the worst platforms I have ever worked with 😢 Using their website from my holiday in India is also the worst, for some reason they think serving an unminified uncompressed 4MB javascript file is fine for everyone 😭
