### ISSUE TITLE
What is the password variable in the phpredisadmin Docker environment?

### ISSUE THREAD

**Issue by inernoro** [erikdubbelboer/phpRedisAdmin#137]
> https://hub.docker.com/r/erikdubbelboer/phpredisadmin/

> Also,

 a Docker Compose manifest with a stack for testing and development is provided. Just issue docker-compose up --build to start it and browse to http://localhost. See docker-compose.yml file for configuration details.

> Where is the docker-compose.yml ?
> I couldn't find all the places.
> I want to link my redis-server with password 
> What is the password variable in the phpredisadmin Docker environment?
> -e REDIS_1_PASSWD=<PASSWORD> or -e REDIS_1_PASSWORD=<PASSWORD> or other?

**Comment by erikdubbelboer** [comment]
It is `REDIS_1_AUTH`. See for example: https://github.com/erikdubbelboer/phpRedisAdmin/issues/136

I have no idea how Docker Compose works so I'm afraid I can't answer that part.

**Comment by inernoro** [comment]
> It is `REDIS_1_AUTH`. See for example: #136
> 
> I have no idea how Docker Compose works so I'm afraid I can't answer that part.

thank you, 
I recommend putting environmental variables in prominent places, such as README.MD. rather than let us look for it.  In addition, that your introduction has docker-compose. If you need it, I can provide you with a docker-compose mini-version.

**Comment by erikdubbelboer** [comment]
@pataquets added all the Docker code. I have never used docker before so I'm not sure what do add where.

If you can make a pull request for these changes that would be greatly appreciated.
