### ISSUE TITLE
Tengine config error

### ISSUE THREAD

**Issue by surpass1990** [erikdubbelboer/phpRedisAdmin#140]
version: Tengine/2.1.2 (nginx/1.6.2)
configuration login error:
`Parse error: syntax error, unexpected '[' in /data/www/monitor/phpRedisAdmin/includes/login.inc.php on line 83 Call Stack: 0.0008 734344 1. {main}() /data/www/monitor/phpRedisAdmin/index.php:0 0.0012 796016 2. require_once('/data/www/monitor/phpRedisAdmin/includes/common.inc.php') /data/www/monitor/phpRedisAdmin/index.php:3`

**Comment by surpass1990** [comment]
用的php5.3. 将出错的位置的'[]' 用 array()代替即可

**Comment by erikdubbelboer** [comment]
我已经把问题解决了，它现在能使用php5.3了。
