### ISSUE TITLE
Nginx proxy config issue

### ISSUE THREAD

**Issue by Dryymoon** [erikdubbelboer/phpRedisAdmin#147]
Hi, 
how i can configure nginx reverse proxy for phpRedisAdmin with subdirectory,
for example like this https://dubbelboer.com/phpRedisAdmin/
(phpRedisAdmin - is subdirectory).

My config:

```
location ~* /redisAdmin/ {
        rewrite ^/redisAdmin/(.*)$ /$1 break;
        proxy_pass http://redisAdmin;
        access_log  off;
    }
```

works, but its not enought for all actions in UI.

**Comment by erikdubbelboer** [comment]
This should be fixed in the latest release. See: https://github.com/erikdubbelboer/phpRedisAdmin/commit/0e8e4724be4016f75608aafd1c260b6f3350c490
