### ISSUE TITLE
2 changes I'd like to implement

### ISSUE THREAD

**Issue by tessus** [erikdubbelboer/phpRedisAdmin#149]
The current code shows all databases with no information:

<img width="212" alt="image" src="https://user-images.githubusercontent.com/223439/68987326-d7144300-07f6-11ea-8fd7-c27fb0c1136c.png">

I'd like to implement 2 changes:

- add a count next to the name (and shorten the name to db)
  database 0 with 666 keys would then look like this: `db 0 (666)` or `db0 (666)`
- create an option to list only databases with keys

Please let me know what you think. I can create a PR or 2...

**Comment by erikdubbelboer** [comment]
Sounds like a good idea. You can combine it in one PR.

**Comment by tessus** [comment]
Cool, it would look like this:

<img width="227" alt="image" src="https://user-images.githubusercontent.com/223439/68997939-fa340680-0879-11ea-97ca-02fa62b9e156.png">

Or do you want to keep the prefix `database `?

<img width="260" alt="image" src="https://user-images.githubusercontent.com/223439/68997951-16d03e80-087a-11ea-877c-5ac0af6540a6.png">

# Default value

Also, what should be the default? Hiding or showing empty databases?

**Comment by erikdubbelboer** [comment]
The Redis documentation says `database` so lets keep that I guess.

I think the default should be to show empty databases. Not showing them might confuse users who have a database but then don't see it.

**Comment by tessus** [comment]
> The Redis documentation says database so lets keep that I guess.

Right, but internally (e.g. config output) they are always referenced as `dbX`. I've added a variable (not an option), so you can change it easily.

> I think the default should be to show empty databases. Not showing them might confuse users who have a database but then don't see it.

Ok, makes sense.

PR's coming up in a sec.
