### ISSUE TITLE
switching db should show overview

### ISSUE THREAD

**Issue by tessus** [erikdubbelboer/phpRedisAdmin#151]
Currently if a key is selectetd and one switches the database, an error `This key does not exist.` is shown right away.
However, it should show the overview instead. Showing an error every time another database is selected is a bit weird.

**Comment by tessus** [comment]
This is similar to #89.

Thus switching the server or the database should always show the overview page.

**Comment by erikdubbelboer** [comment]
A pull request would be welcome. I don't have time at the moment to fix this I'm afraid.

**Comment by tessus** [comment]
Ok, I will have a look at it when I get to it. Also, `method_exists($redis, 'resetstat')` is always returning false, because that method does not exist (bug in phpredis documentation)
