### ISSUE TITLE
Laragon and Laravel

### ISSUE THREAD

**Issue by K2ouMais** [erikdubbelboer/phpRedisAdmin#161]
Hello everyone,

I am using phpRedisAdmin local and I was trying to cache some API responses to Redis.

One thing was driving me crazy. I know I was caching to Redis, but i couldnt see any keys cached.

My Laravel was caching to DB 1 and for some reason, there isnt a way to change DBs in phpRedisAdmin or am I missing something?

I could see my cache over Redis CLI, but I wanted to see it in phpRedisAdmin.

Thanks in advance

**Comment by erikdubbelboer** [comment]
You can configure the db to use in your server config: https://github.com/erikdubbelboer/phpRedisAdmin/blob/1ee43ae7c2ad415cc99086575d66dfd9df6831fb/includes/config.sample.inc.php#L28
