### ISSUE TITLE
Function get_magic_quotes_gpc() is deprecated

### ISSUE THREAD

**Issue by malohtie** [erikdubbelboer/phpRedisAdmin#162]
This Function it been deprecated in php 7.4 

![image](https://user-images.githubusercontent.com/20033279/92994410-e5ec8480-f4f1-11ea-9f9b-d628ad2c7cbb.png)

**Comment by erikdubbelboer** [comment]
You must me using an old version of phpRedisAdmin, this function was removed at the start of this year: https://github.com/erikdubbelboer/phpRedisAdmin/pull/158

**Comment by malohtie** [comment]
Great im using the version that ship with laragon, would be nice if you add into the footer of page phpRedisAdmin version
