### ISSUE TITLE
Parse error: syntax error, unexpected '?' in \phpredisadmin\vendor\src\Client.php on line 60

### ISSUE THREAD

**Issue by a6965921** [erikdubbelboer/phpRedisAdmin#164]
不支持PHP5.4？？

**Comment by erikdubbelboer** [comment]
How did you install phpredisadmin?

**Comment by a6965921** [comment]
git clone https://github.com/ErikDubbelboer/phpRedisAdmin.git
cd phpRedisAdmin
git clone https://github.com/nrk/predis.git vendor

php5.4 can't support ?? grammar

**Comment by erikdubbelboer** [comment]
You can't just `git clone https://github.com/nrk/predis.git vendor`. That version is not compatible with phpRedisAdmin or with your PHP version.

You can fix it using:
```
cd vendor/predis
git checkout v1.1.6
```

**Comment by venu-ibex-9** [comment]
I am getting this issue, can anyone help me with this?

Fatal error: Uncaught Predis\Response\ServerException: ERR unknown command 'CONFIG' in /src/app/vendor/predis/predis/src/Client.php:370 Stack trace: #0 /src/app/vendor/predis/predis/src/Client.php(335): Predis\Client->onErrorResponse(Object(Predis\Command\ServerConfig), Object(Predis\Response\Error)) #1 /src/app/vendor/predis/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\ServerConfig)) #2 /src/app/index.php(209): Predis\Client->__call('config', Array) #3 {main} thrown in /src/app/vendor/predis/predis/src/Client.php on line 370

**Comment by erikdubbelboer** [comment]
@venu-ibex-9 please check https://github.com/erikdubbelboer/phpRedisAdmin/issues/102
