### ISSUE TITLE
Arm64 docker image

### ISSUE THREAD

**Issue by nervo** [erikdubbelboer/phpRedisAdmin#176]
Hi :)
Thanks for your hard work on PhpRedisAdmin ! Do you plan to provide an arm64 based docker image ?

**Comment by erikdubbelboer** [comment]
I have just pushed an image to test this. Can you please test `erikdubbelboer/phpredisadmin:test-arm64`? Thanks.

**Comment by nervo** [comment]
Amazing 🥇
I've just tested `erikdubbelboer/phpredisadmin:test-arm64` on my mac M1, and it works :)

Dude, you're awesone ❤️

**Comment by erikdubbelboer** [comment]
Pushed it to the `latest` tag as well now. From now on I'll release each update as arm64 image as well.
