### ISSUE TITLE
Why no tags for new versions?

### ISSUE THREAD

**Issue by r7l** [erikdubbelboer/phpRedisAdmin#178]
Why is this project not using tags? Github allows to only be notified on new releases. I've activated this some time ago and never got any notification since new release are just announced as commit messages.

On the other hand, having tags allows easier packaging for those not using Docker. I would actually be interested to create a package for Gentoo Linux. I am not using phpRedisAdmin with Docker.

**Comment by erikdubbelboer** [comment]
Every version is tagged in git: https://github.com/erikdubbelboer/phpRedisAdmin/tags
But the Github release feature was never used, I will do that from now on.

**Comment by r7l** [comment]
You're correct and i am sorry for mixing it up. I was misled by the version being stuck on the right side of the project and by Github not sending me any notifications.
