### ISSUE TITLE
Please support semantic versioning

### ISSUE THREAD

**Issue by matsn0w** [erikdubbelboer/phpRedisAdmin#186]
Hi there,

Thank you for your hard work!

I have a suggestion: use proper semantic versioning for your Docker image tags. You now only have specific `major.minor.patch` tags available. 

For example, it would be nice if you'd also tag your latest `1.17.x` as `1.17`. And `1.17` also as `1`. That way, people can deside on what upgrade path they'd like to ride. 

See [the Composer image](https://hub.docker.com/_/composer) as an example!

I also suggest removing the 'v' character in the tags, it's not necessary.

Thank you in advance!
matsn0w

**Comment by erikdubbelboer** [comment]
Good idea. I have created the tags and will do so for any future releases: https://hub.docker.com/r/erikdubbelboer/phpredisadmin/tags
