### ISSUE TITLE
Unable to delete keys with comma(s)

### ISSUE THREAD

**Issue by KarelWintersky** [erikdubbelboer/phpRedisAdmin#187]
My keys list:

![изображение](https://user-images.githubusercontent.com/2164874/196998078-33c9b5f2-9b6e-4561-9305-92f43a25483b.png)

I select `Articles.All(rid=11,did=14,page=12)` and press "Delete selected"

Nothing changed, but I recieved:

![изображение](https://user-images.githubusercontent.com/2164874/196998450-a5fc4771-40f8-40c0-863c-a9fe2f74a816.png)

`Select All -> Delete selected` broken too with same situation on screen above

Click on key 

![изображение](https://user-images.githubusercontent.com/2164874/196998760-50c7bad7-6307-441d-8863-906417e02f08.png)

and click on red cross works, with answer:

![изображение](https://user-images.githubusercontent.com/2164874/196998935-e6e29cb9-483e-4294-9f90-cd967a397b24.png)
(just as planned)

P.S. Keys with `(`, `)` and `,` allowed by redis:

![изображение](https://user-images.githubusercontent.com/2164874/196999403-a22012ef-1f9b-42b7-8d9e-e8aa527772cd.png)

**Comment by KarelWintersky** [comment]
Update: 

Problem with `,` symbol. 

![изображение](https://user-images.githubusercontent.com/2164874/197002487-590321c7-b2c0-4d68-8f74-000a8adcc353.png)

**Comment by erikdubbelboer** [comment]
I can't seem to reproduce this. But I see in some of your screenshots that the last `)` seems to be missing. Do you have any idea what might be causing this?

Can you give me some steps to reproduce this on an empty database? Like which keys to create and which buttons to press?

**Comment by KarelWintersky** [comment]
![изображение](https://user-images.githubusercontent.com/2164874/197336755-e85b0f13-f77b-4ffb-950f-fee8e9077fde.png)

Press "+ Add another key"

![изображение](https://user-images.githubusercontent.com/2164874/197336788-e9b09dac-2021-4556-912b-52a195de6f33.png)

Press "Add"

![изображение](https://user-images.githubusercontent.com/2164874/197336801-abab79f7-29ea-4ac1-b9e8-d4ff9febcfda.png)

All okey... may be...

Press "Select all"

![изображение](https://user-images.githubusercontent.com/2164874/197336814-3fcb0c1d-76ad-425c-a78d-e5db95ce231e.png)

Press "Delete selected"

![изображение](https://user-images.githubusercontent.com/2164874/197336824-4e3d76f3-89fc-473f-ba08-7e8ee609d715.png)

Click on key again: 

![изображение](https://user-images.githubusercontent.com/2164874/197336834-b39f3d49-c735-4e36-88e9-2043c4104352.png)

Already present.

**Comment by KarelWintersky** [comment]
Looks like problem in on frontend, because POST request have broken data:

![изображение](https://user-images.githubusercontent.com/2164874/197337045-d2d41d5f-a544-4f06-863e-53e6390de68e.png)

so, https://github.com/erikdubbelboer/phpRedisAdmin/blob/master/delete.php#L63 will recieve only
```
"Articles(x"
```

**Comment by KarelWintersky** [comment]
I think, problem is here: 

A bit later (average at ~ evening of sunday) I can make pull request :)

I think, problem is here: 
https://github.com/erikdubbelboer/phpRedisAdmin/blob/master/js/index.js#L31
'post=1&selected_keys=' + selected_keys + '&csrf=' + phpRedisAdmin_csrfToken
```
data: {
post: 1,
selected_keys: JSON.stringify(selected_keys),
csrf: phpRedisAdmin_csrfToken
}
```
+ json_decode of given data on backside

**Comment by erikdubbelboer** [comment]
Good find, that definitely needs to be turned into a JSON body. If you can make a pull request that would be great!

**Comment by KarelWintersky** [comment]
Also, A LOT of minor bugs and ugly code are in project... 

Also, I recommend up minimal PHP Version to 7.2 (or 7.4)
