### ISSUE TITLE
php 8.2 quirks

### ISSUE THREAD

**Issue by skliarie** [erikdubbelboer/phpRedisAdmin#196]
Latest docker image at erikdubbelboer/phpredisadmin uses php8.2 and reveals several compatibility warnings.
Several "Warning: Cannot modify header information - headers already sent" that I suppressed (but should really be fixed):

```
vi /src/app/includes/common.inc.php 
ini_set('display_errors', FALSE);

```
And deprecated ${var} with {$var}:
```
vi /src/app/index.php
:157
Replace
      $dbinfo = sprintf("$prefix%'.-${padding}d", $d);
with
      $dbinfo = sprintf("$prefix%'.-{$padding}d", $d);

```

**Comment by erikdubbelboer** [comment]
I have released a new container that should fix this.
