### ISSUE TITLE
sites:get_sites

### ISSUE THREAD

**Issue by alexlii1971** [erikdubbelboer/phpRedisAdmin#200]
Hello,

I am quite new with phpRedisAdmin, there is only one main site of multisite of my wordpress, but there is a list of [phpRedisAdmin](sites:get_sites), please check the screenshot:

https://prnt.sc/tasN5PlAXvQf

Is this expected? if not, how should I fix it, please?

Thanks

**Comment by erikdubbelboer** [comment]
I'm sorry this is not a wordpress support forum. phpRedisAdmin just shows what is in your redis instance. If you don't understand what is in there I suggest asking the thing that put it there.
