### ISSUE TITLE
scanmax issue

### ISSUE THREAD

**Issue by tessus** [erikdubbelboer/phpRedisAdmin#211]
<img width="220" alt="image" src="https://github.com/user-attachments/assets/d1c05e2a-2b70-489c-a226-87bfec741f9f">

This is the end of my `config.inc.php`:

```
  // How many entries to fetch using each SCAN command.
  'scansize' => 1000,

  // In each query, SCAN command may be executed several times. To shorten the duration, it is recommended to limit the total number of entries to fetch.
  'scanmax'   => 10000
);
```

So, my `scanmax` is set to 10000, yet I get the message that scanmax reached. btw, this db has only arounf 8000 keys. So, the scanmax should never be reached.

**Comment by erikdubbelboer** [comment]
Not sure what might be happening, the logic makes sense. You're going to have to debug this yourself: https://github.com/erikdubbelboer/phpRedisAdmin/blob/47f4c678f0cca20709a2587c2704c0ec612de189/index.php#L258

**Comment by tessus** [comment]
Do you accept a PR for the 2 issues I mentioned above?

**Comment by erikdubbelboer** [comment]
Yes please. Sorry I haven't gotten the time to look into it myself yet.

**Comment by tessus** [comment]
Will do. Might get to it on the weekend..

**Comment by tessus** [comment]
While fixing the code I have noticed that it is not possible to not use a scanmax value and there's a bit of a default value issue.

2 scenarios:

- I don't want a `scanmax` (same behavior as before it was implemented, which means read all keys) 
- what happens if `scanmax` (or `scansize`) is not set? it's rather an undefined behavior.

`scanmax` and `scansize` must be set either on the global level or in the server context. If not, weird things happen.

I suggest to set `scansize` to `1000`, if it is not set anywhere.
`scanmax` should allow the value `0` or `-1` to not have a limit at all, which was the behavior before `scanmax` was implemented.
After that I suggest to have that as the default value, if it is not set in the config file (globally or server level).

Otherwise it is not backwards compatible and people run into issues, if they update phpRedisAdmin without adjusting their config file.

Please let me know what you think.

**Comment by erikdubbelboer** [comment]
Sounds good to me 👍

**Comment by tessus** [comment]
In this case, please check out the PR. ;-)
