### ISSUE TITLE
syntax error 1.21.1

### ISSUE THREAD

**Issue by jaegwon** [erikdubbelboer/phpRedisAdmin#213]
Parse error: syntax error, unexpected single-quoted string "scanmax", expecting ")" in /src/app/includes/config.sample.inc.php on line 90

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Fixed the syntax error on line 90 of config.sample.inc.php by adding a comma after the 'scansize' configuration and removing the extra parenthesis.

You can review changes in this commit: https://github.com/mnmnk43434/erikdubbelboer-phpRedisAdmin-213/commit/fb9d2db14e69cbc5858fc9ca6112daf1cedc94af.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by jaegwon** [comment]
Deprecated: Predis\Client::createPipeline(): Implicitly marking parameter $options as nullable is deprecated, the explicit nullable type must be used instead in /src/app/vendor/predis/predis/src/Client.php on line 429

Deprecated: Predis\Client::createTransaction(): Implicitly marking parameter $options as nullable is deprecated, the explicit nullable type must be used instead in /src/app/vendor/predis/predis/src/Client.php on line 472

Deprecated: Predis\Client::createPubSub(): Implicitly marking parameter $options as nullable is deprecated, the explicit nullable type must be used instead in /src/app/vendor/predis/predis/src/Client.php on line 504

Deprecated: Predis\Profile\RedisProfile::setProcessor(): Implicitly marking parameter $processor as nullable is deprecated, the explicit nullable type must be used instead in /src/app/vendor/predis/predis/src/Profile/RedisProfile.php on line 124

Warning: Cannot modify header information - headers already sent by (output started at /src/app/vendor/predis/predis/src/Client.php:429) in /src/app/includes/header.inc.php on line 5

Warning: Cannot modify header information - headers already sent by (output started at /src/app/vendor/predis/predis/src/Client.php:429) in /src/app/includes/header.inc.php on line 6

Warning: Cannot modify header information - headers already sent by (output started at /src/app/vendor/predis/predis/src/Client.php:429) in /src/app/includes/header.inc.php on line 7
