### ISSUE TITLE
Request: auto list databases and select from there

### ISSUE THREAD

**Issue by seansan** [ErikDubbelboer/phpRedisAdmin#35]
Hi, now the config requires 

'name' => 'local db 2',
'host' => 'localhost',
'port' => 6379,
'db'   => 1 // Optional database number
'filter' => 'something:*'

Our request is as follows
- if 'db' is set to * then a new dropdown or sub in the hierarchy is shown with a list of all databases that I can select from
- The problem is that we often dont 'remember' which database numbers are configured. 
- This way we can first see 'all the databases uner 1 port'
- and from there zoom in, per database

I hope you understand ;)

Thanks for the great work

**Comment by joeyhub** [comment]
It is that command.

With phpredis I use:

$redis->config('GET', 'databases')['databases'];

It should be similar in predis.

**Comment by ErikDubbelboer** [comment]
I have now added an extra dropdown box to select the database if there are multiple.
