### ISSUE TITLE
Resize key frame

### ISSUE THREAD

**Issue by Maraumax** [ErikDubbelboer/phpRedisAdmin#47]
Hello,

Thanks for that tool. It would be great allow resize keys frame when we have long keys.

My long keys :
![](https://cloud.githubusercontent.com/assets/194488/2829038/eab86270-cf9d-11e3-9f0b-305bd6d450fc.jpg)

**Comment by basvandorst** [comment]
+1 

@flenczewski: You're right, but sometimes you would like to resize the whole sidebar (and not only to scroll inside the sidebar).

**Comment by ErikDubbelboer** [comment]
It's added to the latest version.
