### ISSUE TITLE
Request: Refresh keys without refreshing page/frame

### ISSUE THREAD

**Issue by deancsmith** [ErikDubbelboer/phpRedisAdmin#62]
Sometimes I'm looking at a specific set of keys, e.g. 'failed' below, and I want to refresh/update the values within they key without refreshing the whole page.

![image](https://cloud.githubusercontent.com/assets/387289/4934602/077df244-65a3-11e4-8b85-b1da682e773b.png)

Would it be possible to have a refresh button next to the key name and ajax them in? Or assign an anchor tag to each key, and have the refresh button refresh the page but jump down to the anchor you clicked and auto-expand the node?

(This is really just an ease-of-use suggestion; otherwise I am finding this to be a really handy tool)

**Comment by wf9a5m75** [comment]
How about use Elephant.io (socket.io client fully written in PHP) ?
http://elephant.io/

Using Socket.io, you can push data from server side to client side.

**Comment by ErikDubbelboer** [comment]
Elephant.io is a socket.io client. It's not possible to use it to push messages to the client, for that you need a socket.io server.

**Comment by wf9a5m75** [comment]
https://github.com/RickySu/phpsocket.io

**Comment by wf9a5m75** [comment]
Well, this is kind of old code, but it seems this code works as websocket server.
https://github.com/Flynsarmy/PHPWebSocket-Chat

Another alternative is http://socketo.me/
Looks well-documented software.

**Comment by ErikDubbelboer** [comment]
All these solutions need you to start a separate PHP process on the command line which I don't really like.

All of this really over complicates things in my opinion. The simplest way is still just to make a filter (you can even do this on a separate server config and then refresh that.
