### ISSUE TITLE
Bug in ConnectionFactory::create() Method

### ISSUE THREAD

**Issue by wendoscoo** [ErikDubbelboer/phpRedisAdmin#64]
In  /vendor/predis/predis/lib/Predis/Connection/ConnectionFactory.php 

I found there is a bug in ConnectionFactory::create() method.
This bug may cause "Connection refuse exception" in Predis::Client() , because the ConnectionFactory::create() method will always use the paramters defined in ConnectionParameters::$defaults;

I made a small change to fix this bug ,see the screenshot blow:

Before:
![2](https://cloud.githubusercontent.com/assets/2849142/5625949/4e75ea84-95bf-11e4-986b-b6fbb3914cd6.png)

After:
![1](https://cloud.githubusercontent.com/assets/2849142/5625968/8abcfd0c-95bf-11e4-97d8-4d04adbf38e3.png)

That will works when we need to connect to another remote server by phpRedisAdmin.

**Comment by wendoscoo** [comment]
![1](https://cloud.githubusercontent.com/assets/2849142/5625956/5daebbca-95bf-11e4-96e0-64b5f4eefee9.png)

**Comment by ErikDubbelboer** [comment]
Predis is not part of this project but is a dependency. But this is not a bug with them either, this is a special syntax shorthand in PHP that does exactly the same as your fix.

```php
erik@localhost:~$ php
<?php
$a = array('foo' => 'bar');
var_dump($a ?: array());
$a = null;
var_dump($a ?: array());

array(1) {
  ["foo"]=>
  string(3) "bar"
}
array(0) {
}
```
