### ISSUE TITLE
Questionable Feature Request: Handle serialization?

### ISSUE THREAD

**Issue by joeyhub** [ErikDubbelboer/phpRedisAdmin#69]
I use binary serialization in redis.

It has the disadvantage that you need to handle more complex data than just strings but a number of serious advantages as well over using JSON and just making the string editable.

Advantages:
* Faster.
* Uses much less memory.
* Preserves types accurately (arrays).
* Does not have problems with character sets/binary data.

My work around for this is to make my encoder json -> igbinary and the decoder vice versa.

You could use the same solution with the serializer functions configurable (msgpack, igbinary, php, json, json pretty, etc).

This loses a key advantage of type preservation.

The catch 22 is that for the front end it would really want to be in JSON anyway so you still bump into those problems with PHP and indeterminate array type or JSON/JS and their charset issues. Though at the very least using a common JSON editing library would be nice.

On a side note, you have ?> at the end of files and then white space. This forces the use of output buffering even when it may not be necessary which increases memory usage a lot.

It is best to just not have the closing tag in include files even if you intend not to have a new line. Some tools like a new line at the end so people tend to add one as good practice. You cannot do this with ?> at the end of an include file without the ob.

Another side note, my json solution works well enough, though in your display you do not use white space pre.

Finally, I have some massive serialized objects but there is no way to effectively deal with these here.

It looks like early work but the first tool I've found where I am able to edit redis that is igbinary backed with relative easy and minimal setup cost.

**Comment by ErikDubbelboer** [comment]
Can you maybe summarize what this issue is about? Do I understand correctly that you want to be able to edit binary data or json from the phpRedisAdmin editor?

**Comment by joeyhub** [comment]
Hello,

The basic issue is that a lot of people don't use the basic native types in redis to store raw data. It's very common to do something like serialize data structures such as associative arrays as strings in redis.

A simple way to think of it is like this:
put($key, serialize($data));
get($key, unserialize($data));

For performance and so forth many of us use things like igbinary_serialize, msgpack, etc.

Most redis tools only support JSON, if they support anything at all. This means that when you look at the data you just see binary junk. It means most tools are little good for more than seeing what keys exist and the size of things.

Some people might serialize complex things but lucking for me this works fine:

put($key, igbinary_serialize(json_decode($data)));
get($key, json_encode(igbinary_unserialize($data), JSON_PRETTY_PRINT));

This lets me view the content of my documents and also allows me to edit them so phpRedisAdmin becomes a much more powerful debugging tools for me.

Thanks.

**Comment by ErikDubbelboer** [comment]
I have been thinking about this, how about if we add a new config option where you can add key pattern and encode/decode functions to use for that pattern. So for example if you want to serialize all keys which start with foo you would use:

```php
<?
$config = array(
  ...

  'serialization' => array(
    'foo*' => array(
      'decode' => function($data) { return igbinary_serialize(json_decode($data)); },
      'encode' => function($data) { return json_encode(igbinary_unserialize($data), JSON_PRETTY_PRINT)); },
    )
  ),

  ...
```

Using just `'*'` would serialize all keys (like the redis `KEYS` pattern).

This way people can specify their own encoding schemes for different keys.

Would this work for you?

**Comment by joeyhub** [comment]
This would work well for everyone :).

In mine I made it * and only for string/hash type as these are all I use.

The only other thing is that in mine I duct-taped it by switching nl2br with white-space: pre...

index 4c48cb6..5b5ed8c
--- a/view.php
+++ b/view.php
@@ -172,7 +172,7 @@
-<tr><td><div><?php echo nl2br(format_html($value))?></div></td><td><div>
+<tr><td><div style="white-space: pre;"><?php echo format_html($value)?></div></td><td><div>
@@ -190,7 +190,7 @@
-  <tr <?php echo $alt ? 'class="alt"' : ''?>><td><div><?php echo format_html($hkey)?></div></td><td><div><?php echo nl2br(format_html($value))?></div></td><td><div>
+  <tr <?php echo $alt ? 'class="alt"' : ''?>><td><div><?php echo format_html($hkey)?></div></td><td><div style="white-space: pre;"><?php echo format_html($value)?></div></td><td><div>

(context stripped)

**Comment by ErikDubbelboer** [comment]
I pushed a test version to a custom branch: https://github.com/ErikDubbelboer/phpRedisAdmin/tree/customencode

Can you test and see if this works for you? Thanks.

**Comment by joeyhub** [comment]
Thanks, will do at the first opportunity :).

**Comment by ErikDubbelboer** [comment]
I just merged it into master as I think it should work :)

**Comment by gumutianqi** [comment]
the unserialize is not work

**Comment by ErikDubbelboer** [comment]
What `load` function are you using? If it works or not depends completely on the `load` and `save` function you provide or the data already present in Redis.

**Comment by gumutianqi** [comment]
@ErikDubbelboer 

I'm sorry!  It is working properly in English.

but the serialization does not support Chinese.

And what do I need to support serialization Chinese?

**Comment by ErikDubbelboer** [comment]
If I don't know what your `save` and `load` functions look like I can not know. I'm guessing it is some problem with PHP and unicode support.

**Comment by gumutianqi** [comment]
I use the java code:
my characters is utf-8

```java
Serializer g_ser = new FSTSerializer();
g_ser.serialize(value);
or
g_ser.deserialize(value);
```

**Comment by gumutianqi** [comment]
and the key(Chinese characters) is properly, value is not.

**Comment by gumutianqi** [comment]
The Redis 3.0.5 is not work, the serialization English characters view 'null'

**Comment by erikdubbelboer** [comment]
I need more information on what exactly you are doing and what software you are using. As you can see here Chinese characters shouldn't be an issue: http://dubbelboer.com/phpRedisAdmin/?view&s=0&d=0&key=test

**Comment by gumutianqi** [comment]
open new issues #85 .

Thanks for attention to my problem.
