### ISSUE TITLE
Not support msgpack format display

### ISSUE THREAD

**Issue by sinabs** [ErikDubbelboer/phpRedisAdmin#71]
I hoping to support [msgpack](http://msgpack.org/) value format display
![msg](https://cloud.githubusercontent.com/assets/1351257/8157988/90eaf25c-138b-11e5-8f6b-a911c9c3c2c8.png)

**Comment by ErikDubbelboer** [comment]
I just merged a new feature which allows you to specify a custom encoding. When you install https://github.com/msgpack/msgpack-php the following config should work (I haven't tested it):
```php
  'serialization' => array(
    '*' => array( // Match like KEYS
      // Function called when saving to redis.
      'save' => function($data) { return msgpack_pack($data); },
      // Function called when loading from redis.
      'load' => function($data) { return msgpack_unpack($data); },
    ),
  ),
```

See: https://github.com/ErikDubbelboer/phpRedisAdmin/blob/master/includes/config.sample.inc.php#L57
