### ISSUE TITLE
error after install

### ISSUE THREAD

**Issue by arteck** [ErikDubbelboer/phpRedisAdmin#74]
Fatal error: Uncaught exception 'Predis\Response\ServerException' with message 'ERR unknown command 'SCAN'' in /var/www/phpRedisAdmin/vendor/src/Client.php:367 Stack trace: #0 /var/www/phpRedisAdmin/vendor/src/Client.php(332): Predis\Client->onErrorResponse(Object(Predis\Command\KeyScan), Object(Predis\Response\Error)) #1 /var/www/phpRedisAdmin/vendor/src/Client.php(312): Predis\Client->executeCommand(Object(Predis\Command\KeyScan)) #2 /var/www/phpRedisAdmin/index.php(14): Predis\Client->__call('scan', Array) #3 /var/www/phpRedisAdmin/index.php(14): Predis\Client->scan(0, 'MATCH', '*', 'COUNT', 1000) #4 {main} thrown in /var/www/phpRedisAdmin/vendor/src/Client.php on line 367

**Comment by ErikDubbelboer** [comment]
phpRedisAdmin uses the `SCAN` command to get all keys in your keyspace. You are using a super old version of redis (from 2013) which doesn't support this command yet. You need to set `keys => true` in your config file. See: https://github.com/ErikDubbelboer/phpRedisAdmin/blob/99ba128623371f3d9702b7ec890bf114d37480b6/includes/config.sample.inc.php#L73

**Comment by fbens** [comment]
I have the same problem too,after change the `keys` from `false` to `true`, problem resolved.
file: `includes/config.inc.php`
