### ISSUE TITLE
phpRedisAdmin Can’t connect to this server

### ISSUE THREAD

**Issue by aleafboat** [ErikDubbelboer/phpRedisAdmin#75]
this my config.inc.php
$config = array(
  'servers' => array(
    array(
      'name'   => 'troy', // Optional name.
      'host'   => '192.168.113.141',
      'port'   => 6379,
      'filter' => '*',
but i  can use redis-cli to connect

**Comment by aleafboat** [comment]
; Directory in which the loadable extensions (modules) reside.
; http://php.net/extension-dir
; extension_dir = "./"
extension_dir = "/usr/lib64/php/modules" 
extension=redis.so

**Comment by ErikDubbelboer** [comment]
Is your php/webserver on the same host you tried redis-cli from? Is phpRedisAdmin a blank page or a can't connect page?

**Comment by PangeaServers** [comment]
i got the same problem on debian. it tells me "Server Down" on the page.

**Comment by aleafboat** [comment]
yes， it is the same host ,and phpRedisAdmin  is not a blank page

**Comment by ErikDubbelboer** [comment]
```
redis-cli -h 192.168.113.141 -p 6379
```
Works on that same host phpRedisAdmin is on?

What exactly is the redis.so extension? phpRedisAdmin uses https://github.com/nrk/predis which doesn't require any extensions.
