### ISSUE TITLE
AWS Elasticache usage

### ISSUE THREAD

**Issue by martinfobian** [ErikDubbelboer/phpRedisAdmin#76]
I'm trying to get this to run for an AWS Elasticache Redis instance. I stumbled upon a couple of sources that report, that Elasticache doesn't allow the CONFIG command. Is there any way to get aroung this (even maybe with limited functionality) or will this not work with any Redis Admin UI?

**Comment by ErikDubbelboer** [comment]
I just pushed a new version which allows you to set the number of databases in your config. See [config.sample.inc.php](https://github.com/ErikDubbelboer/phpRedisAdmin/blob/d344599f6c3e4bd080fe3d0f243a561c55b1a7f9/includes/config.sample.inc.php#L26). This will prevent the CONFIG command from being used.
