### ISSUE TITLE
Fatal error in redis 3.0

### ISSUE THREAD

**Issue by grasses** [ErikDubbelboer/phpRedisAdmin#77]
Fatal error: Uncaught exception 'Predis\Response\ServerException' with message 'ERR unknown command 'SCAN'' in /www/vendor/predis/predis/src/Client.php:367 Stack trace: #0 /www/phpRedisAdmin/vendor/predis/predis/src/Client.php(332): Predis\Client->onErrorResponse(Object(Predis\Command\KeyScan), Object(Predis\Response\Error)) #1 /www/phpRedisAdmin/vendor/predis/predis/src/Client.php(312): Predis\Client->executeCommand(Object(Predis\Command\KeyScan)) #2 /www/phpRedisAdmin/index.php(14): Predis\Client->__call('scan', Array) #3 /www/phpRedisAdmin/index.php(14): Predis\Client->scan(0, 'MATCH', '*', 'COUNT', 1000) #4 {main} thrown in /www/phpRedisAdmin/vendor/predis/predis/src/Client.php on line 367

**Comment by ErikDubbelboer** [comment]
`ERR unknown command SCAN` shows me that you are using redis 2.8.0 or older which is at least more than 2 years old. I would suggest updating your redis.

If you can't this you can also tell phpRedisAdmin to use the old and slow `KEYS *` command: [includes/config.sample.inc.php#L74](https://github.com/ErikDubbelboer/phpRedisAdmin/blob/master/includes/config.sample.inc.php#L74)
