### ISSUE TITLE
after redis-benchmark can not load redis admin page ?

### ISSUE THREAD

**Issue by centminmod** [ErikDubbelboer/phpRedisAdmin#78]
After a few redis-benchmarks with

    redis-benchmark -h 127.0.0.1 -p 6379 -r 1000000 -n 2000000 -t get,set,lpush,lpop -P 16 -q

going to my installed php redis admin page in web browser just ends up spinning with loading icon then ends with a blank page ?

    redis-cli -h 127.0.0.1 -p 6379 info
    # Server
    redis_version:3.0.4
    redis_git_sha1:00000000
    redis_git_dirty:0
    redis_build_id:f984dc706585cedc
    redis_mode:standalone
    os:Linux 3.10.0-229.11.1.el7.x86_64 x86_64
    arch_bits:64
    multiplexing_api:epoll
    gcc_version:4.8.3
    process_id:20643
    run_id:c46d3ff66cde5f945141a75bbf615c0688663ec5
    tcp_port:6379
    uptime_in_seconds:2414
    uptime_in_days:0
    hz:10
    lru_clock:528437
    config_file:/etc/redis.conf
    
    # Clients
    connected_clients:1
    client_longest_output_list:0
    client_biggest_input_buf:0
    blocked_clients:0
    
    # Memory
    used_memory:95881312
    used_memory_human:91.44M
    used_memory_rss:110108672
    used_memory_peak:222726984
    used_memory_peak_human:212.41M
    used_memory_lua:36864
    mem_fragmentation_ratio:1.15
    mem_allocator:jemalloc-3.6.0
    
    # Persistence
    loading:0
    rdb_changes_since_last_save:0
    rdb_bgsave_in_progress:0
    rdb_last_save_time:1443367663
    rdb_last_bgsave_status:ok
    rdb_last_bgsave_time_sec:1
    rdb_current_bgsave_time_sec:-1
    aof_enabled:1
    aof_rewrite_in_progress:0
    aof_rewrite_scheduled:0
    aof_last_rewrite_time_sec:2
    aof_current_rewrite_time_sec:-1
    aof_last_bgrewrite_status:ok
    aof_last_write_status:ok
    aof_current_size:111473175
    aof_base_size:55750096
    aof_pending_rewrite:0
    aof_buffer_length:0
    aof_rewrite_buffer_length:0
    aof_pending_bio_fsync:0
    aof_delayed_fsync:0
    
    # Stats
    total_connections_received:272
    total_commands_processed:9330917
    instantaneous_ops_per_sec:0
    total_net_input_bytes:333826251
    total_net_output_bytes:450040084
    instantaneous_input_kbps:0.00
    instantaneous_output_kbps:0.00
    rejected_connections:0
    sync_full:0
    sync_partial_ok:0
    sync_partial_err:0
    expired_keys:0
    evicted_keys:0
    keyspace_hits:2042823
    keyspace_misses:303881
    pubsub_channels:0
    pubsub_patterns:0
    latest_fork_usec:3321
    migrate_cached_sockets:0
    
    # Replication
    role:master
    connected_slaves:0
    master_repl_offset:0
    repl_backlog_active:0
    repl_backlog_size:1048576
    repl_backlog_first_byte_offset:0
    repl_backlog_histlen:0
    
    # CPU
    used_cpu_sys:13.38
    used_cpu_user:71.54
    used_cpu_sys_children:0.71
    used_cpu_user_children:3.25
    
    # Cluster
    cluster_enabled:0
    
    # Keyspace
    db0:keys=902823,expires=0,avg_ttl=0

**Comment by ErikDubbelboer** [comment]
phpRedisAdmin can't handle too many keys because it's written in PHP. With 902823 keys PHP probably takes to long to generate the page. You have some options:
 * Either increase your PHP/webserver timeout (possibly also increase max memory usage).
 * Use something like https://redsmin.com/ instead of phpRedisAdmin.
 * Try the [faster](https://github.com/ErikDubbelboer/phpRedisAdmin/blob/master/includes/config.sample.inc.php#L41) option.
 * Use a [filter](https://github.com/ErikDubbelboer/phpRedisAdmin/blob/master/includes/config.sample.inc.php#L27) to only show a subset of all the keys.

**Comment by centminmod** [comment]
:+1: thanks @ErikDubbelboer :)
