### ISSUE TITLE
ERR unknown command 'CONFIG

### ISSUE THREAD

**Issue by xdexter** [ErikDubbelboer/phpRedisAdmin#80]
Hello, I am having trouble in using the phpredisadmin with ElastiCache on Amazon Web Service, when setting the redis have the following error:

2015/10/08 19:27:54 [error] 28723#0: *23262 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Predis\Response\ServerException' with message 'ERR unknown command 'CONFIG'' in /srv/www/htdocs/default/phpRedisAdmin/vendor/src/Client.php:365
Stack trace:
#0 /srv/www/htdocs/default/phpRedisAdmin/vendor/src/Client.php(330): Predis\Client->onErrorResponse(Object(Predis\Command\ServerConfig), Object(Predis\Response\Error))
#1 /srv/www/htdocs/default/phpRedisAdmin/vendor/src/Client.php(310): Predis\Client->executeCommand(Object(Predis\Command\ServerConfig))
#2 /srv/www/htdocs/default/phpRedisAdmin/index.php(176): Predis\Client->__call('config', Array)
#3 /srv/www/htdocs/default/phpRedisAdmin/index.php(176): Predis\Client->config('GET', 'databases')
#4 {main}
  thrown in /srv/www/htdocs/default/phpRedisAdmin/vendor/src/Client.php on line 365" while reading response header from upstream, client: 189.7.9.21, server: default, request: "GET /phpRedisAdmin/?info&s=1&d=5 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "IP", referrer: "http://IP/phpRedisAdmin/?info&s=0&d=5"

This should work or is there some kind of restriction?

thanks in advance

**Comment by ErikDubbelboer** [comment]
You have to specify the number of databases in your config so the `CONFIG` command doesn't need to be used. See: [includes/config.sample.inc.php](https://github.com/ErikDubbelboer/phpRedisAdmin/blob/3fa986f7f782babd758b504852a4aeffb89363bd/includes/config.sample.inc.php#L26)

**Comment by xdexter** [comment]
Perfect!

Thank you
