### ISSUE TITLE
It's better to write a supported redis version list in the README

### ISSUE THREAD

**Issue by gouchaoer** [ErikDubbelboer/phpRedisAdmin#81]
This project depends on predis and points out the predis version. That's good. But on some Redis version, phpRedisAdmin doesn't work although the predis works. For example, my redis version is 2.4.10 on centos6.5, Predis 1.0.1 works fine but phpRedisAdmin doesn't work because redis 2.4.10 doesn't support 'SCAN' command.

**Comment by ErikDubbelboer** [comment]
This has nothing to do with predis. As you can see on http://redis.io/commands/scan the scan command is available as of redis 2.8.0.

For this reason we have thet `keys` configuration option to disable the use of `SCAN`. See [includes/config.sample.inc.php](https://github.com/ErikDubbelboer/phpRedisAdmin/blob/3fa986f7f782babd758b504852a4aeffb89363bd/includes/config.sample.inc.php#L74)

**Comment by gouchaoer** [comment]
That's right...I enable the use of keys in config.inc.php and it works.
