### ISSUE TITLE
Javascript needs to be enabled for you to delete keys.

### ISSUE THREAD

**Issue by BigKuCha** [ErikDubbelboer/phpRedisAdmin#82]
when I delete keys ,it show me that ! How to fix it? thanks.
error in chrome console:
`Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL xxx`
error in firefox console:
`SecurityError: The operation is insecure.`

**Comment by ErikDubbelboer** [comment]
Which browser are you using?

**Comment by BigKuCha** [comment]
chrome and firefox

**Comment by ErikDubbelboer** [comment]
What domain did you deploy phpRedisAdmin on? Normally this should never happen as it only tries to replace it's own state.

**Comment by BigKuCha** [comment]
Mac osx 10.10.5

**Comment by ErikDubbelboer** [comment]
I mean which domain as in http://example.com

**Comment by BigKuCha** [comment]
http://local.phpredisadmin.com/?view&s=0&d=1&key=name

**Comment by BigKuCha** [comment]
The problem is solved.I changed domain from  `http://local.phpredisadmin.com` to `http://phpredisadmin` . Hope you can improve it.Thanks!  :smile:
