### ISSUE TITLE
on redis 2.4, I can't select database

### ISSUE THREAD

**Issue by gouchaoer** [ErikDubbelboer/phpRedisAdmin#83]
PHP Notice:  Undefined index: databases in /home/website/phpredisadmin/index.php on line 180

As I debug into the index.php, I found:

**Comment by gouchaoer** [comment]
$databases = $redis->config('GET', 'databases');
this line return nothing for my redis version, which makes my phpRedisAdmin can't select database.
So I change it like this and solved the problem.
$databases = $redis->config('GET', 'databases');
$databases = $databases['databases'];
$databases=16;//which is dirty

I hope phpRedisAdmin could do some effort to support more redis versions. No need to  change something in config.inc.php, make phpRedisAdmin available for all redis versions. You know people used phpRedisAdmin for they know a little about php

**Comment by ErikDubbelboer** [comment]
You do realize that redis 2.4 is more than 3 years old an nobody supports it anymore? I'm also not going to support such an old version.

**Comment by frankbret** [comment]
Idem with redislabs rdis free subscription.  Databases are not send so "Undefined index" notice trouble.  Not a show stopper but...
