### ISSUE TITLE
Serialization display problems

### ISSUE THREAD

**Issue by gumutianqi** [erikdubbelboer/phpRedisAdmin#85]
@erikdubbelboer 
I use the following code serialization, but view `'null'`
```
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

import net.sf.ehcache.CacheException;
import org.nustaq.serialization.FSTObjectInput;
import org.nustaq.serialization.FSTObjectOutput;

/**
 * 使用 FST 实现序列化
 * @author winterlau
 */
public class FSTSerializer implements Serializer {

	@Override
	public String name() {
		return "fst";
	}

	@Override
	public byte[] serialize(Object obj) throws IOException {
		ByteArrayOutputStream out = null;
		FSTObjectOutput fout = null;
		try {
			out = new ByteArrayOutputStream();
			fout = new FSTObjectOutput(out);
			fout.writeObject(obj);
			fout.flush();
			return out.toByteArray();
		} finally {
			if(fout != null)
			try {
				fout.close();
			} catch (IOException e) {}
		}
	}

	@Override
	public Object deserialize(byte[] bytes) throws IOException {
		if(bytes == null || bytes.length == 0)
			return null;
		FSTObjectInput in = null;
		try {
			in = new FSTObjectInput(new ByteArrayInputStream(bytes));
			return in.readObject();
		} catch (ClassNotFoundException e) {
			throw new CacheException(e);
		} finally {
			if(in != null)
			try {
				in.close();
			} catch (IOException e) {}
		}
	}

}
```

**Comment by erikdubbelboer** [comment]
I don't see anything related to Redis in there. As I showed you in the other issue, if things are put into Redis in a proper way there is no issue with Chinese characters: http://dubbelboer.com/phpRedisAdmin/?view&s=0&d=0&key=test
It looks like this has nothing to do with phpRedisAdmin.

**Comment by gumutianqi** [comment]
This is my way of data serialization,
After treatment stored Redis, in phpMyRedis not display properly.

**Comment by erikdubbelboer** [comment]
You're using some Java Serialization library to turn a Java object into a stream of bytes. I'm not even sure what you expect to see in phpRedisAdmin? Can you show me the data that you have in Redis?

**Comment by gumutianqi** [comment]
My phpRedisAdmin is as a tool in use, the same as phpMyAdmin.I don't  know whether such a Java Serialization can be displayed phpRedisAdmin data

**Comment by erikdubbelboer** [comment]
Of course phpRedisAdmin doesn't know how you data is encoded and how you want it to be displayed. By default it assumes the data is just a string and tries to show it as that. If you want phpRedisAdmin to understand your data you have to specify a custom [`load` function in your config](https://github.com/erikdubbelboer/phpRedisAdmin/blob/3fa986f7f782babd758b504852a4aeffb89363bd/includes/config.sample.inc.php#L63) that will decode the data into a string that phpRedisAdmin can show.

**Comment by gumutianqi** [comment]
thanks, I will continue to try.
