### ISSUE TITLE
Got error 'PHP message: PHP Warning:  require(/var/www/html/phpRedisAdmin/includes/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/phpRedisAdmin/includes/common.inc.php on line 2

### ISSUE THREAD

**Issue by oxzhor** [erikdubbelboer/phpRedisAdmin#97]
Hi,

I try to install phpRedisAdmin into /var/www/html/phpRedisAdmin on centos 6.7 x64 incl DirectAdmin and redis but i get a white page when i goto http://serverip/phpRedisAdmin

The error log show the follow:

`[Thu May 19 19:16:13.353010 2016] [proxy_fcgi:error] [pid 24249:tid 140195384968960] [client 94.211.*.*:50320] AH01071: Got error 'PHP message: PHP Warning:  require(/var/www/html/phpRedisAdmin/includes/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/phpRedisAdmin/includes/common.inc.php on line 2\nPHP message: PHP Fatal error:  require(): Failed opening required '/var/www/html/phpRedisAdmin/includes/../vendor/autoload.php' (include_path='.:/usr/local/php56/lib/php') in /var/www/html/phpRedisAdmin/includes/common.inc.php on line 2\n'`

How i can solved this problem?

Regards

**Comment by erikdubbelboer** [comment]
This means you didn't install the dependencies. Please follow the instructions at [README.markdown#installingconfiguring](https://github.com/erikdubbelboer/phpRedisAdmin/blob/master/README.markdown#installingconfiguring)
