### ISSUE TITLE
ncaught exception 'Predis\\Response\\ServerException' with message 'ERR unknown command 'SCAN''

### ISSUE THREAD

**Issue by oxzhor** [erikdubbelboer/phpRedisAdmin#98]
Hi,

I installed phpRedisAdmin via composer:
`curl -s http://getcomposer.org/installer | php
php composer.phar create-project -s dev erik-dubbelboer/php-redis-admin /var/www/html/phpRedisAdmin
cd phpRedisAdmin/includes; cp config.sample.inc.php config.inc.php`

Go to http://serverip/phpRedisAdmin and get a white screen. In the apache error log i see the follow error:
`Got error 'PHP message: PHP Fatal error:  Uncaught exception 'Predis\\Response\\ServerException' with message 'ERR unknown command 'SCAN'' in /var/www/html/phpRedisAdmin/vendor/predis/predis/src/Client.php:365\nStack trace:\n#0 /var/www/html/phpRedisAdmin/vendor/predis/predis/src/Client.php(330): Predis\\Client->onErrorResponse(Object(Predis\\Command\\KeyScan), Object(Predis\\Response\\Error))\n#1 /var/www/html/phpRedisAdmin/vendor/predis/predis/src/Client.php(310): Predis\\Client->executeCommand(Object(Predis\\Command\\KeyScan))\n#2 /var/www/html/phpRedisAdmin/index.php(14): Predis\\Client->__call('scan', Array)\n#3 /var/www/html/phpRedisAdmin/index.php(14): Predis\\Client->scan(0, 'MATCH', '*', 'COUNT', 1000)\n#4 {main}\n  thrown in /var/www/html/phpRedisAdmin/vendor/predis/predis/src/Client.php on line 365\n'
`
How we can solved this issue?

**Comment by erikdubbelboer** [comment]
You are using a **3 year old** version of Redis which doesn't support the `SCAN` command. I would suggest you upgrade to a newer version, or if you can't for some reason you have to tell phpRedisAdmin to use the slower `KEYS` command instead: https://github.com/erikdubbelboer/phpRedisAdmin/blob/3a2655dde6bcc58d72770256bdbf0ec66e54f8d8/includes/config.sample.inc.php#L76

**Comment by oxzhor** [comment]
Hi i am running the last stable version 3.2.0

**Comment by erikdubbelboer** [comment]
Your error says: `ERR unknown command 'SCAN'`. And http://redis.io/commands/scan says `Available since 2.8.0.`.

**Comment by oxzhor** [comment]
Thx erik the repo has a old version i reinstall redis now from source and it works.

The post can close.
