### ISSUE TITLE
can not connnet to redis-sentinel

### ISSUE THREAD

**Issue by ganting** [erikdubbelboer/phpRedisAdmin#99]
redis version: 2.8.21

Fatal error: Uncaught Predis\NotSupportedException: Cannot use 'SCAN' over clusters of connections. in /src/app/vendor/predis/predis/src/Connection/Aggregate/PredisCluster.php:134 Stack trace: #0 /src/app/vendor/predis/predis/src/Connection/Aggregate/PredisCluster.php(215): Predis\Connection\Aggregate\PredisCluster->getConnection(Object(Predis\Command\KeyScan)) #1 /src/app/vendor/predis/predis/src/Client.php(326): Predis\Connection\Aggregate\PredisCluster->executeCommand(Object(Predis\Command\KeyScan)) #2 /src/app/vendor/predis/predis/src/Client.php(309): Predis\Client->executeCommand(Object(Predis\Command\KeyScan)) #3 /src/app/index.php(14): Predis\Client->__call('scan', Array) #4 {main} thrown in /src/app/vendor/predis/predis/src/Connection/Aggregate/PredisCluster.php on line 134

**Comment by erikdubbelboer** [comment]
You are using a **3 year old** version of Redis which doesn't support the `SCAN` command. I would suggest you upgrade to a newer version, or if you can't for some reason you have to tell phpRedisAdmin to use the slower `KEYS` command instead: https://github.com/erikdubbelboer/phpRedisAdmin/blob/3a2655dde6bcc58d72770256bdbf0ec66e54f8d8/includes/config.sample.inc.php#L76

**Comment by aymhce** [comment]
Hello, I have this same issue. I use redis 3.2.11 and phpRedisAdmin 1.8.0

Fatal error: Uncaught Predis\Response\ServerException: ERR unknown command 'SCAN' in /src/app/vendor/predis/predis/src/Client.php:365 Stack trace: #0 /src/app/vendor/predis/predis/src/Client.php(330): Predis\Client->onErrorResponse(Object(Predis\Command\KeyScan), Object(Predis\Response\Error)) #1 /src/app/vendor/predis/predis/src/Client.php(309): Predis\Client->executeCommand(Object(Predis\Command\KeyScan)) #2 /src/app/index.php(14): Predis\Client->__call('scan', Array) #3 {main} thrown in /src/app/vendor/predis/predis/src/Client.php on line 365

**Comment by erikdubbelboer** [comment]
@aymhce the `SCAN` command has been available since Redis `2.8.0`. So either your version is incorrect or the command is disabled for some reason? Either way the solution above should work.

**Comment by jianzhong** [comment]
@aymhce I don't think phpRedisAdmin is supporting Sentinel at the moment. Redis Sentinel has its own command set. Commands for Redis are not supported when you are connecting to a Sentinel instance. SCAN is a Redis command, and cannot be understood by Sentinel. This is why you got this error. The predis started supporting Sentinel from v1.1.0. This software is using predis v1.0.3. Do wish this software supports Sentinel in the future.
